const fs = require('fs')
const path = require('path')

const exams = ['CGL', 'CHSL', 'CPO']
const years = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

const raw = [
  // Computer Fundamentals
  { st: 'Computer Fundamentals', q: 'The brain of a computer is called:', o: { A: 'ALU', B: 'CPU', C: 'Memory', D: 'Hard Disk' }, c: 'B', ex: 'The CPU (Central Processing Unit) is known as the brain of the computer.' },
  { st: 'Computer Fundamentals', q: 'Which of the following is an input device?', o: { A: 'Monitor', B: 'Printer', C: 'Keyboard', D: 'Speaker' }, c: 'C', ex: 'A keyboard is an input device. Monitor, printer, and speaker are output devices.' },
  { st: 'Computer Fundamentals', q: '1 Kilobyte (KB) is equal to:', o: { A: '1000 Bytes', B: '1024 Bytes', C: '1024 Bits', D: '1000 Bits' }, c: 'B', ex: '1 KB = 2^10 = 1024 Bytes.' },
  { st: 'Computer Fundamentals', q: 'Which generation of computers used Integrated Circuits?', o: { A: 'First', B: 'Second', C: 'Third', D: 'Fourth' }, c: 'C', ex: 'Third generation (1964-1971) used ICs.' },
  { st: 'Computer Fundamentals', q: 'RAM stands for:', o: { A: 'Random Access Memory', B: 'Read Access Memory', C: 'Run Access Memory', D: 'Random Allocation Memory' }, c: 'A', ex: 'RAM = Random Access Memory, volatile temporary storage.' },
  { st: 'Computer Fundamentals', q: 'Which of the following is NOT a type of computer?', o: { A: 'Mainframe', B: 'Supercomputer', C: 'Compiler', D: 'Minicomputer' }, c: 'C', ex: 'A compiler is software, not a type of computer.' },
  { st: 'Computer Fundamentals', q: 'USB stands for:', o: { A: 'Universal Serial Bus', B: 'Universal System Bus', C: 'Unique Serial Bus', D: 'United Serial Bus' }, c: 'A', ex: 'USB = Universal Serial Bus.' },
  { st: 'Computer Fundamentals', q: 'Which memory is non-volatile?', o: { A: 'RAM', B: 'ROM', C: 'Cache', D: 'Register' }, c: 'B', ex: 'ROM retains data even when power is off.' },
  { st: 'Computer Fundamentals', q: 'The binary number system has a base of:', o: { A: '2', B: '8', C: '10', D: '16' }, c: 'A', ex: 'Binary uses base 2 with digits 0 and 1.' },
  { st: 'Computer Fundamentals', q: 'Which device converts digital signals to analog?', o: { A: 'Router', B: 'Modem', C: 'Switch', D: 'Hub' }, c: 'B', ex: 'A modem modulates/demodulates signals.' },
  { st: 'Computer Fundamentals', q: 'BIOS stands for:', o: { A: 'Basic Input Output System', B: 'Binary Input Output System', C: 'Basic Integrated Operating System', D: 'Binary Integrated Output System' }, c: 'A', ex: 'BIOS = Basic Input Output System.' },
  { st: 'Computer Fundamentals', q: 'Which is an example of optical storage?', o: { A: 'Hard Disk', B: 'Pen Drive', C: 'CD-ROM', D: 'Floppy Disk' }, c: 'C', ex: 'CD-ROM uses laser technology.' },
  { st: 'Computer Fundamentals', q: 'ASCII stands for:', o: { A: 'American Standard Code for Information Interchange', B: 'American Standard Code for International Interchange', C: 'Asian Standard Code for Information Interchange', D: 'American System Code for Information Interchange' }, c: 'A', ex: 'ASCII = American Standard Code for Information Interchange.' },
  { st: 'Computer Fundamentals', q: 'Which is a secondary storage device?', o: { A: 'RAM', B: 'Cache', C: 'Hard Disk', D: 'Register' }, c: 'C', ex: 'Hard Disk is permanent secondary storage.' },
  { st: 'Computer Fundamentals', q: 'The process of starting a computer is called:', o: { A: 'Formatting', B: 'Booting', C: 'Processing', D: 'Networking' }, c: 'B', ex: 'Booting loads the OS into memory.' },
  { st: 'Computer Fundamentals', q: 'ALU stands for:', o: { A: 'Arithmetic Logic Unit', B: 'Application Logic Unit', C: 'Arithmetic Linear Unit', D: 'Applied Logic Unit' }, c: 'A', ex: 'ALU performs arithmetic and logical operations in the CPU.' },
  { st: 'Computer Fundamentals', q: 'How many bits make one byte?', o: { A: '4', B: '8', C: '16', D: '32' }, c: 'B', ex: 'One byte = 8 bits.' },
  { st: 'Computer Fundamentals', q: 'The smallest unit of data in a computer is:', o: { A: 'Byte', B: 'Bit', C: 'Nibble', D: 'Word' }, c: 'B', ex: 'A bit (0 or 1) is the smallest data unit.' },
  { st: 'Computer Fundamentals', q: 'Which is a high-level language?', o: { A: 'Machine Language', B: 'Assembly Language', C: 'Python', D: 'Binary Code' }, c: 'C', ex: 'Python is a high-level language.' },
  { st: 'Computer Fundamentals', q: 'Which unit controls all parts of the computer?', o: { A: 'ALU', B: 'Control Unit', C: 'Memory', D: 'Output Unit' }, c: 'B', ex: 'The Control Unit coordinates all computer operations.' },
  { st: 'Computer Fundamentals', q: 'VGA stands for:', o: { A: 'Video Graphics Array', B: 'Visual Graphics Array', C: 'Video Graphic Adapter', D: 'Visual Graphic Adapter' }, c: 'A', ex: 'VGA = Video Graphics Array.' },
  { st: 'Computer Fundamentals', q: 'Which is volatile memory?', o: { A: 'ROM', B: 'EPROM', C: 'RAM', D: 'PROM' }, c: 'C', ex: 'RAM loses data when power is off.' },
  { st: 'Computer Fundamentals', q: 'Which language is often called the mother of all languages?', o: { A: 'Python', B: 'Java', C: 'C', D: 'FORTRAN' }, c: 'C', ex: 'C influenced many modern languages.' },
  { st: 'Computer Fundamentals', q: 'Supercomputers are primarily used for:', o: { A: 'Word processing', B: 'Complex scientific calculations', C: 'Playing games', D: 'Internet browsing' }, c: 'B', ex: 'Supercomputers handle complex scientific simulations.' },
  { st: 'Computer Fundamentals', q: 'EEPROM stands for:', o: { A: 'Electrically Erasable Programmable Read-Only Memory', B: 'Electronic Erasable Programmable Read-Only Memory', C: 'Extended Erasable Programmable Read-Only Memory', D: 'Enhanced Erasable Programmable Read-Only Memory' }, c: 'A', ex: 'EEPROM = Electrically Erasable Programmable Read-Only Memory.' },

  // Operating Systems
  { st: 'Operating Systems', q: 'Which is NOT an operating system?', o: { A: 'Windows', B: 'Linux', C: 'Oracle', D: 'macOS' }, c: 'C', ex: 'Oracle is a DBMS, not an OS.' },
  { st: 'Operating Systems', q: 'Linux is an example of:', o: { A: 'Closed source OS', B: 'Open source OS', C: 'Application software', D: 'Utility software' }, c: 'B', ex: 'Linux is open-source.' },
  { st: 'Operating Systems', q: 'The main function of an OS is to:', o: { A: 'Compile programs', B: 'Manage computer resources', C: 'Create documents', D: 'Browse internet' }, c: 'B', ex: 'OS manages hardware and software resources.' },
  { st: 'Operating Systems', q: 'Which OS is used in most smartphones?', o: { A: 'Windows', B: 'Linux', C: 'Android', D: 'macOS' }, c: 'C', ex: 'Android is the most widely used mobile OS.' },
  { st: 'Operating Systems', q: 'Swapping in OS is:', o: { A: 'Caching', B: 'Moving inactive processes to secondary storage', C: 'Buffering', D: 'Spooling' }, c: 'B', ex: 'Swapping frees main memory by moving inactive processes.' },
  { st: 'Operating Systems', q: 'Ctrl+Alt+Delete in Windows opens:', o: { A: 'File Explorer', B: 'Security screen / Task Manager', C: 'Settings', D: 'Calculator' }, c: 'B', ex: 'Ctrl+Alt+Delete opens the security screen.' },
  { st: 'Operating Systems', q: 'Multitasking means:', o: { A: 'Running one program at a time', B: 'Running multiple programs simultaneously', C: 'Running programs sequentially', D: 'Running in batch mode' }, c: 'B', ex: 'Multitasking runs multiple programs at once.' },
  { st: 'Operating Systems', q: 'Which file system is used by Windows?', o: { A: 'ext4', B: 'NTFS', C: 'HFS+', D: 'XFS' }, c: 'B', ex: 'NTFS is the primary Windows file system.' },
  { st: 'Operating Systems', q: 'A deadlock occurs when:', o: { A: 'A process is terminated', B: 'Processes wait indefinitely for resources held by each other', C: 'CPU is idle', D: 'Memory is full' }, c: 'B', ex: 'Deadlock is a circular resource dependency.' },
  { st: 'Operating Systems', q: 'UNIX was developed at:', o: { A: 'Microsoft', B: 'Apple', C: 'Bell Labs', D: 'IBM' }, c: 'C', ex: 'UNIX was developed at Bell Labs in 1969.' },
  { st: 'Operating Systems', q: 'Virtual memory uses:', o: { A: 'RAM only', B: 'Hard disk as extended RAM', C: 'Cache memory', D: 'ROM' }, c: 'B', ex: 'Virtual memory extends RAM using disk space.' },
  { st: 'Operating Systems', q: 'Which command lists files in Linux?', o: { A: 'dir', B: 'ls', C: 'list', D: 'show' }, c: 'B', ex: 'ls lists directory contents in Linux.' },
  { st: 'Operating Systems', q: 'GUI stands for:', o: { A: 'General User Interface', B: 'Graphical User Interface', C: 'Graphical Unified Interface', D: 'General Unified Interface' }, c: 'B', ex: 'GUI = Graphical User Interface.' },
  { st: 'Operating Systems', q: 'Which is a real-time OS?', o: { A: 'Windows 10', B: 'Ubuntu', C: 'VxWorks', D: 'macOS' }, c: 'C', ex: 'VxWorks is an RTOS for embedded systems.' },
  { st: 'Operating Systems', q: 'Kernel is:', o: { A: 'A type of software', B: 'The core of an operating system', C: 'A hardware component', D: 'A type of virus' }, c: 'B', ex: 'The kernel manages system resources.' },
  { st: 'Operating Systems', q: 'Thrashing occurs when:', o: { A: 'CPU utilization is high', B: 'System spends more time swapping pages than executing', C: 'There is a deadlock', D: 'Memory is full' }, c: 'B', ex: 'Thrashing severely degrades performance.' },
  { st: 'Operating Systems', q: 'The shortcut to rename a file in Windows is:', o: { A: 'F2', B: 'F5', C: 'F3', D: 'F4' }, c: 'A', ex: 'F2 renames the selected file.' },
  { st: 'Operating Systems', q: 'A process in an OS is:', o: { A: 'A stored program', B: 'A program in execution', C: 'A compiled program', D: 'An installed software' }, c: 'B', ex: 'A process is a program currently executing.' },
  { st: 'Operating Systems', q: 'SJF scheduling gives:', o: { A: 'Maximum throughput', B: 'Minimum average waiting time', C: 'Maximum response time', D: 'Minimum CPU usage' }, c: 'B', ex: 'Shortest Job First minimizes average waiting time.' },
  { st: 'Operating Systems', q: 'The Recycle Bin stores:', o: { A: 'Permanently deleted files', B: 'Temporarily deleted files', C: 'System files', D: 'Backup files' }, c: 'B', ex: 'Files can be restored from the Recycle Bin.' },
  { st: 'Operating Systems', q: 'Which is NOT a type of OS?', o: { A: 'Batch OS', B: 'Time-sharing OS', C: 'Compiler OS', D: 'Distributed OS' }, c: 'C', ex: 'Compiler OS does not exist; a compiler is a translator.' },
  { st: 'Operating Systems', q: 'The .exe extension indicates:', o: { A: 'A text file', B: 'An executable file', C: 'An image file', D: 'A system file' }, c: 'B', ex: '.exe files are executable programs.' },
  { st: 'Operating Systems', q: 'Which OS component manages files?', o: { A: 'Process Manager', B: 'Memory Manager', C: 'File Manager', D: 'Device Manager' }, c: 'C', ex: 'The File Manager handles file operations.' },

  // MS Office
  { st: 'MS Office', q: 'Which software creates spreadsheets?', o: { A: 'MS Word', B: 'MS Excel', C: 'MS PowerPoint', D: 'MS Access' }, c: 'B', ex: 'MS Excel is the spreadsheet application.' },
  { st: 'MS Office', q: 'Shortcut to save in MS Word:', o: { A: 'Ctrl+V', B: 'Ctrl+S', C: 'Ctrl+P', D: 'Ctrl+N' }, c: 'B', ex: 'Ctrl+S saves the document.' },
  { st: 'MS Office', q: 'A cell in Excel is identified by:', o: { A: 'Row number only', B: 'Column letter only', C: 'Column letter and row number', D: 'Sheet name' }, c: 'C', ex: 'E.g., A1, B5, C10.' },
  { st: 'MS Office', q: 'Which view rearranges slides in PowerPoint?', o: { A: 'Normal View', B: 'Slide Sorter View', C: 'Reading View', D: 'Outline View' }, c: 'B', ex: 'Slide Sorter shows all slides as thumbnails.' },
  { st: 'MS Office', q: 'Default extension of MS Word 2016:', o: { A: '.doc', B: '.docx', C: '.txt', D: '.rtf' }, c: 'B', ex: '.docx is default since Word 2007.' },
  { st: 'MS Office', q: 'Excel function for average:', o: { A: 'SUM', B: 'AVERAGE', C: 'COUNT', D: 'MAX' }, c: 'B', ex: 'AVERAGE calculates arithmetic mean.' },
  { st: 'MS Office', q: 'Mail Merge is a feature of:', o: { A: 'MS Excel', B: 'MS PowerPoint', C: 'MS Word', D: 'MS Access' }, c: 'C', ex: 'Mail Merge creates personalized documents.' },
  { st: 'MS Office', q: 'Shortcut to undo:', o: { A: 'Ctrl+Y', B: 'Ctrl+Z', C: 'Ctrl+X', D: 'Ctrl+U' }, c: 'B', ex: 'Ctrl+Z undoes the last action.' },
  { st: 'MS Office', q: 'Maximum rows in Excel 2016:', o: { A: '65,536', B: '1,048,576', C: '256', D: '16,384' }, c: 'B', ex: 'Excel 2007+ supports 1,048,576 rows.' },
  { st: 'MS Office', q: 'Which function returns the largest value?', o: { A: 'MIN', B: 'LARGE', C: 'MAX', D: 'HIGH' }, c: 'C', ex: 'MAX returns the largest value.' },
  { st: 'MS Office', q: 'Header and Footer appear on:', o: { A: 'First page only', B: 'Last page only', C: 'Every page', D: 'Alternate pages' }, c: 'C', ex: 'They appear on every page by default.' },
  { st: 'MS Office', q: 'Shortcut to start slideshow in PowerPoint:', o: { A: 'F5', B: 'F7', C: 'F9', D: 'F11' }, c: 'A', ex: 'F5 starts from the first slide.' },
  { st: 'MS Office', q: 'Default extension of MS Excel:', o: { A: '.xls', B: '.xlsx', C: '.csv', D: '.xlsm' }, c: 'B', ex: '.xlsx is default since Excel 2007.' },
  { st: 'MS Office', q: 'Which app is used for database management?', o: { A: 'MS Word', B: 'MS Excel', C: 'MS Access', D: 'MS Outlook' }, c: 'C', ex: 'MS Access is a DBMS.' },
  { st: 'MS Office', q: 'VLOOKUP stands for:', o: { A: 'Vertical Lookup', B: 'Value Lookup', C: 'Variable Lookup', D: 'Visual Lookup' }, c: 'A', ex: 'VLOOKUP = Vertical Lookup.' },
  { st: 'MS Office', q: 'Shortcut for bold text:', o: { A: 'Ctrl+I', B: 'Ctrl+U', C: 'Ctrl+B', D: 'Ctrl+D' }, c: 'C', ex: 'Ctrl+B toggles bold.' },
  { st: 'MS Office', q: 'Best chart for showing proportions:', o: { A: 'Bar Chart', B: 'Line Chart', C: 'Pie Chart', D: 'Scatter Plot' }, c: 'C', ex: 'Pie Chart shows parts of a whole.' },
  { st: 'MS Office', q: 'AutoSum in Excel:', o: { A: 'Formats cells', B: 'Adds values in a range', C: 'Saves files', D: 'Creates charts' }, c: 'B', ex: 'AutoSum inserts a SUM formula.' },
  { st: 'MS Office', q: 'Ctrl+P is the shortcut for:', o: { A: 'Paste', B: 'Print', C: 'Page setup', D: 'Preview' }, c: 'B', ex: 'Ctrl+P opens Print dialog.' },
  { st: 'MS Office', q: 'Portrait and Landscape are:', o: { A: 'Page sizes', B: 'Page orientations', C: 'Margin types', D: 'Layout types' }, c: 'B', ex: 'They are page orientation options.' },
  { st: 'MS Office', q: 'Excel operator for multiplication:', o: { A: 'x', B: '*', C: '#', D: '&' }, c: 'B', ex: 'Asterisk (*) is used for multiplication.' },
  { st: 'MS Office', q: 'Spell Check in MS Word is accessed by:', o: { A: 'F5', B: 'F7', C: 'F9', D: 'F11' }, c: 'B', ex: 'F7 opens Spell Check.' },
  { st: 'MS Office', q: 'Which tab has the table insert option?', o: { A: 'Home', B: 'Insert', C: 'Layout', D: 'View' }, c: 'B', ex: 'Insert tab contains table, picture, chart options.' },
  { st: 'MS Office', q: 'Intersection of row and column in Access:', o: { A: 'Cell', B: 'Record', C: 'Field', D: 'Tuple' }, c: 'C', ex: 'A column represents a Field in Access.' },

  // Networking
  { st: 'Networking', q: 'LAN stands for:', o: { A: 'Local Area Network', B: 'Large Area Network', C: 'Long Area Network', D: 'Linear Area Network' }, c: 'A', ex: 'LAN = Local Area Network.' },
  { st: 'Networking', q: 'Which device connects different networks?', o: { A: 'Hub', B: 'Switch', C: 'Router', D: 'Repeater' }, c: 'C', ex: 'A router connects and routes between networks.' },
  { st: 'Networking', q: 'IP stands for:', o: { A: 'Internet Protocol', B: 'Internal Protocol', C: 'Internet Program', D: 'Integrated Protocol' }, c: 'A', ex: 'IP = Internet Protocol.' },
  { st: 'Networking', q: 'All devices on a single cable is which topology?', o: { A: 'Star', B: 'Ring', C: 'Bus', D: 'Mesh' }, c: 'C', ex: 'Bus topology uses a single backbone cable.' },
  { st: 'Networking', q: 'Which protocol sends emails?', o: { A: 'HTTP', B: 'FTP', C: 'SMTP', D: 'TCP' }, c: 'C', ex: 'SMTP = Simple Mail Transfer Protocol.' },
  { st: 'Networking', q: 'A MAC address is:', o: { A: 'A software address', B: 'A 48-bit hardware address', C: 'An IP address', D: 'A network name' }, c: 'B', ex: 'MAC is a unique 48-bit hardware identifier.' },
  { st: 'Networking', q: 'Which OSI layer handles routing?', o: { A: 'Data Link', B: 'Network', C: 'Transport', D: 'Session' }, c: 'B', ex: 'Network Layer (Layer 3) handles routing.' },
  { st: 'Networking', q: 'HTTP stands for:', o: { A: 'HyperText Transfer Protocol', B: 'High Text Transfer Protocol', C: 'HyperText Transmission Protocol', D: 'Hybrid Text Transfer Protocol' }, c: 'A', ex: 'HTTP = HyperText Transfer Protocol.' },
  { st: 'Networking', q: 'OSI model has how many layers?', o: { A: '5', B: '6', C: '7', D: '8' }, c: 'C', ex: '7 layers in the OSI model.' },
  { st: 'Networking', q: 'DNS stands for:', o: { A: 'Domain Name System', B: 'Digital Network Service', C: 'Data Name System', D: 'Domain Number System' }, c: 'A', ex: 'DNS translates domain names to IP addresses.' },
  { st: 'Networking', q: 'Which topology has highest reliability?', o: { A: 'Bus', B: 'Star', C: 'Ring', D: 'Mesh' }, c: 'D', ex: 'Mesh provides multiple paths for data.' },
  { st: 'Networking', q: 'FTP is used for:', o: { A: 'Sending emails', B: 'Transferring files', C: 'Browsing websites', D: 'Video calling' }, c: 'B', ex: 'FTP = File Transfer Protocol.' },
  { st: 'Networking', q: 'An IPv4 address is:', o: { A: '16-bit', B: '32-bit', C: '64-bit', D: '128-bit' }, c: 'B', ex: 'IPv4 = 32-bit (e.g., 192.168.1.1).' },
  { st: 'Networking', q: 'Which device amplifies signals?', o: { A: 'Router', B: 'Switch', C: 'Repeater', D: 'Bridge' }, c: 'C', ex: 'A Repeater regenerates network signals.' },
  { st: 'Networking', q: 'TCP stands for:', o: { A: 'Transfer Control Protocol', B: 'Transmission Control Protocol', C: 'Total Control Protocol', D: 'Transport Control Protocol' }, c: 'B', ex: 'TCP = Transmission Control Protocol.' },
  { st: 'Networking', q: 'HTTP uses which port?', o: { A: '21', B: '25', C: '80', D: '443' }, c: 'C', ex: 'HTTP = port 80, HTTPS = port 443.' },
  { st: 'Networking', q: 'WAN stands for:', o: { A: 'Wide Area Network', B: 'Wireless Area Network', C: 'Web Area Network', D: 'World Area Network' }, c: 'A', ex: 'WAN = Wide Area Network.' },
  { st: 'Networking', q: 'Which protocol is secure for web browsing?', o: { A: 'HTTP', B: 'FTP', C: 'HTTPS', D: 'SMTP' }, c: 'C', ex: 'HTTPS uses SSL/TLS encryption.' },
  { st: 'Networking', q: 'A firewall:', o: { A: 'Speeds up network', B: 'Protects from unauthorized access', C: 'Stores data', D: 'Connects networks' }, c: 'B', ex: 'Firewalls monitor and control network traffic.' },
  { st: 'Networking', q: 'Which is a private IP address?', o: { A: '192.168.1.1', B: '8.8.8.8', C: '172.217.14.206', D: '216.58.214.206' }, c: 'A', ex: '192.168.x.x is a private IP range.' },
  { st: 'Networking', q: 'Bandwidth is measured in:', o: { A: 'Bytes', B: 'Hertz', C: 'Bits per second', D: 'Watts' }, c: 'C', ex: 'Bandwidth = data transfer rate in bps.' },
  { st: 'Networking', q: 'VPN stands for:', o: { A: 'Virtual Private Network', B: 'Virtual Public Network', C: 'Verified Private Network', D: 'Visual Private Network' }, c: 'A', ex: 'VPN = Virtual Private Network.' },
  { st: 'Networking', q: 'Wi-Fi stands for:', o: { A: 'Wireless Fidelity', B: 'Wired Fidelity', C: 'Wireless Function', D: 'Wide Fidelity' }, c: 'A', ex: 'Wi-Fi = Wireless Fidelity.' },
  { st: 'Networking', q: 'Modem connects computer to:', o: { A: 'Printer', B: 'Telephone line for Internet', C: 'Scanner', D: 'Monitor' }, c: 'B', ex: 'Modem converts digital to analog signals.' },
  { st: 'Networking', q: 'Traditional Ethernet speed:', o: { A: '1 Mbps', B: '10 Mbps', C: '100 Mbps', D: '1 Gbps' }, c: 'B', ex: '10BASE-T Ethernet operates at 10 Mbps.' },

  // Internet & Web
  { st: 'Internet & Web', q: 'WWW stands for:', o: { A: 'World Wide Web', B: 'Wide World Web', C: 'Web World Wide', D: 'World Web Wide' }, c: 'A', ex: 'WWW = World Wide Web.' },
  { st: 'Internet & Web', q: 'HTML stands for:', o: { A: 'HyperText Markup Language', B: 'High Text Machine Language', C: 'HyperText Machine Language', D: 'High Text Markup Language' }, c: 'A', ex: 'HTML = HyperText Markup Language.' },
  { st: 'Internet & Web', q: 'Which is a web browser?', o: { A: 'Google', B: 'Chrome', C: 'Yahoo', D: 'Bing' }, c: 'B', ex: 'Chrome is a browser; others are search engines.' },
  { st: 'Internet & Web', q: 'First page of a website is:', o: { A: 'Index page', B: 'Home page', C: 'Main page', D: 'First page' }, c: 'B', ex: 'The Home page is the first page.' },
  { st: 'Internet & Web', q: 'URL stands for:', o: { A: 'Uniform Resource Locator', B: 'Universal Resource Locator', C: 'Uniform Resource Link', D: 'Universal Resource Link' }, c: 'A', ex: 'URL = Uniform Resource Locator.' },
  { st: 'Internet & Web', q: 'CSS is used for:', o: { A: 'Programming', B: 'Styling web pages', C: 'Database management', D: 'Networking' }, c: 'B', ex: 'CSS styles web page presentation.' },
  { st: 'Internet & Web', q: 'JavaScript is used for:', o: { A: 'Styling', B: 'Making web pages interactive', C: 'Creating databases', D: 'Sending emails' }, c: 'B', ex: 'JavaScript adds interactivity.' },
  { st: 'Internet & Web', q: 'Cookies in browsers:', o: { A: 'Delete data', B: 'Store user information', C: 'Speed up browsing', D: 'Block ads' }, c: 'B', ex: 'Cookies store preferences and session data.' },
  { st: 'Internet & Web', q: 'ISP stands for:', o: { A: 'Internet Service Provider', B: 'Internet System Protocol', C: 'Integrated Service Provider', D: 'Internet Software Program' }, c: 'A', ex: 'ISP = Internet Service Provider.' },
  { st: 'Internet & Web', q: 'Which HTML tag creates hyperlinks?', o: { A: '<link>', B: '<a>', C: '<href>', D: '<url>' }, c: 'B', ex: 'The <a> tag creates hyperlinks.' },
  { st: 'Internet & Web', q: '.gov domain is for:', o: { A: 'Commercial sites', B: 'Educational institutions', C: 'Government websites', D: 'Non-profits' }, c: 'C', ex: '.gov is reserved for government.' },
  { st: 'Internet & Web', q: 'Cloud computing means:', o: { A: 'Computing in the sky', B: 'Using remote servers for data storage and processing', C: 'Weather forecasting', D: 'Using local computers' }, c: 'B', ex: 'Cloud computing uses remote Internet servers.' },
  { st: 'Internet & Web', q: 'Phishing is:', o: { A: 'Online fishing game', B: 'A cyber attack to steal personal info', C: 'Encryption type', D: 'Antivirus software' }, c: 'B', ex: 'Phishing uses fake sites/emails to steal data.' },
  { st: 'Internet & Web', q: 'E-commerce stands for:', o: { A: 'Electronic Commerce', B: 'Easy Commerce', C: 'Extended Commerce', D: 'External Commerce' }, c: 'A', ex: 'E-commerce = Electronic Commerce.' },
  { st: 'Internet & Web', q: 'XML stands for:', o: { A: 'Extended Markup Language', B: 'Extensible Markup Language', C: 'Extra Markup Language', D: 'External Markup Language' }, c: 'B', ex: 'XML = eXtensible Markup Language.' },
  { st: 'Internet & Web', q: 'A blog is:', o: { A: 'A virus', B: 'An online journal or website', C: 'A database', D: 'An OS' }, c: 'B', ex: 'Blog = online journal with regular updates.' },
  { st: 'Internet & Web', q: 'Which is NOT a social media platform?', o: { A: 'Facebook', B: 'Twitter', C: 'Wikipedia', D: 'Instagram' }, c: 'C', ex: 'Wikipedia is an encyclopedia, not social media.' },
  { st: 'Internet & Web', q: 'A bookmark saves:', o: { A: 'Deleted pages', B: 'Links to frequently visited pages', C: 'Blocked websites', D: 'Printed pages' }, c: 'B', ex: 'Bookmarks save links for quick access.' },
  { st: 'Internet & Web', q: 'PHP is a:', o: { A: 'Hardware component', B: 'OS', C: 'Server-side scripting language', D: 'Database' }, c: 'C', ex: 'PHP is a server-side web language.' },
  { st: 'Internet & Web', q: 'Which is NOT a valid email provider?', o: { A: 'Gmail', B: 'Yahoo Mail', C: 'HTML Mail', D: 'Outlook' }, c: 'C', ex: 'HTML Mail is not an email provider.' },
  { st: 'Internet & Web', q: 'An email attachment is:', o: { A: 'A greeting card', B: 'A file sent with an email', C: 'A virus', D: 'A signature' }, c: 'B', ex: 'Attachments are files sent along with emails.' },
  { st: 'Internet & Web', q: 'AJAX stands for:', o: { A: 'Asynchronous JavaScript and XML', B: 'Advanced JavaScript and XML', C: 'Automatic JavaScript and XML', D: 'Applied JavaScript and XML' }, c: 'A', ex: 'AJAX = Asynchronous JavaScript and XML.' },
  { st: 'Internet & Web', q: 'A search engine is used to:', o: { A: 'Create websites', B: 'Find information on the Internet', C: 'Send emails', D: 'Design pages' }, c: 'B', ex: 'Search engines find and retrieve web information.' },
  { st: 'Internet & Web', q: 'HTTPS uses which protocol for security?', o: { A: 'FTP', B: 'SSL/TLS', C: 'SMTP', D: 'POP3' }, c: 'B', ex: 'HTTPS uses SSL/TLS encryption.' },

  // Database Management
  { st: 'Database Management', q: 'DBMS stands for:', o: { A: 'Database Management System', B: 'Digital Base Management System', C: 'Data Basic Management System', D: 'Data Base Maintenance System' }, c: 'A', ex: 'DBMS = Database Management System.' },
  { st: 'Database Management', q: 'SQL stands for:', o: { A: 'Structured Query Language', B: 'Simple Query Language', C: 'Standard Query Language', D: 'Sequential Query Language' }, c: 'A', ex: 'SQL = Structured Query Language.' },
  { st: 'Database Management', q: 'Which SQL retrieves data?', o: { A: 'INSERT', B: 'UPDATE', C: 'SELECT', D: 'DELETE' }, c: 'C', ex: 'SELECT retrieves data from tables.' },
  { st: 'Database Management', q: 'A primary key is:', o: { A: 'Any column', B: 'A unique identifier for each record', C: 'The first column', D: 'A foreign key reference' }, c: 'B', ex: 'Primary key uniquely identifies records.' },
  { st: 'Database Management', q: 'Which is a RDBMS?', o: { A: 'MongoDB', B: 'MySQL', C: 'Redis', D: 'Cassandra' }, c: 'B', ex: 'MySQL is a Relational DBMS.' },
  { st: 'Database Management', q: 'A row in a table is called:', o: { A: 'Field', B: 'Column', C: 'Record', D: 'Key' }, c: 'C', ex: 'A row is a Record (or tuple).' },
  { st: 'Database Management', q: 'Normalization reduces:', o: { A: 'Performance', B: 'Data redundancy', C: 'Data', D: 'Tables' }, c: 'B', ex: 'Normalization minimizes redundancy.' },
  { st: 'Database Management', q: 'A foreign key references:', o: { A: 'Same table primary key', B: 'Primary key of another table', C: 'An encryption key', D: 'A unique key' }, c: 'B', ex: 'Foreign keys link tables together.' },
  { st: 'Database Management', q: 'WHERE clause:', o: { A: 'Sorts records', B: 'Groups records', C: 'Filters records', D: 'Joins tables' }, c: 'C', ex: 'WHERE filters rows by condition.' },
  { st: 'Database Management', q: 'INSERT adds:', o: { A: 'A column', B: 'A new record', C: 'A table', D: 'An index' }, c: 'B', ex: 'INSERT INTO adds new records.' },
  { st: 'Database Management', q: 'A schema defines:', o: { A: 'Data', B: 'Database structure', C: 'Users', D: 'Backups' }, c: 'B', ex: 'Schema defines tables, relationships, constraints.' },
  { st: 'Database Management', q: 'FULL OUTER JOIN returns:', o: { A: 'Matching records only', B: 'Left table records', C: 'Right table records', D: 'All records from both tables' }, c: 'D', ex: 'FULL OUTER JOIN returns all records.' },
  { st: 'Database Management', q: 'DELETE removes:', o: { A: 'A table', B: 'Specific rows', C: 'A database', D: 'A column' }, c: 'B', ex: 'DELETE removes rows based on WHERE.' },
  { st: 'Database Management', q: 'UPDATE modifies:', o: { A: 'Table structure', B: 'Existing data', C: 'Indexes', D: 'Views' }, c: 'B', ex: 'UPDATE changes existing data values.' },
  { st: 'Database Management', q: 'DDL stands for:', o: { A: 'Data Definition Language', B: 'Data Description Language', C: 'Data Derivation Language', D: 'Data Design Language' }, c: 'A', ex: 'DDL = Data Definition Language.' },
  { st: 'Database Management', q: 'A view is:', o: { A: 'A physical table', B: 'A virtual table from a query', C: 'A backup', D: 'An index' }, c: 'B', ex: 'Views are virtual tables based on queries.' },
  { st: 'Database Management', q: 'ACID stands for:', o: { A: 'Atomicity, Consistency, Isolation, Durability', B: 'Addition, Consistency, Integrity, Durability', C: 'Atomicity, Correctness, Isolation, Data', D: 'Addition, Consistency, Isolation, Data' }, c: 'A', ex: 'ACID ensures reliable transactions.' },
  { st: 'Database Management', q: 'DROP TABLE:', o: { A: 'Deletes rows', B: 'Removes table from database', C: 'Truncates data', D: 'Modifies table' }, c: 'B', ex: 'DROP removes the entire table permanently.' },
  { st: 'Database Management', q: 'GROUP BY:', o: { A: 'Sorts', B: 'Groups rows with same values', C: 'Filters', D: 'Joins' }, c: 'B', ex: 'GROUP BY groups rows for aggregate functions.' },
  { st: 'Database Management', q: 'Which is a DML command?', o: { A: 'CREATE', B: 'ALTER', C: 'INSERT', D: 'DROP' }, c: 'C', ex: 'INSERT is DML; CREATE, ALTER, DROP are DDL.' },
  { st: 'Database Management', q: 'Indexing speeds up:', o: { A: 'Deletion', B: 'Data retrieval', C: 'Encryption', D: 'Compression' }, c: 'B', ex: 'Indexes improve query performance.' },
  { st: 'Database Management', q: 'An entity in ER diagram represents:', o: { A: 'A relationship', B: 'An attribute', C: 'A real-world object', D: 'A constraint' }, c: 'C', ex: 'Entities represent real-world objects like Student.' },
  { st: 'Database Management', q: 'A candidate key is:', o: { A: 'Any column', B: 'A minimal super key', C: 'Same as primary key', D: 'A foreign key' }, c: 'B', ex: 'Candidate key = minimal unique identifier.' },
  { st: 'Database Management', q: 'A transaction is:', o: { A: 'A single query', B: 'A unit of work against a database', C: 'Table creation', D: 'A backup' }, c: 'B', ex: 'Transactions must all succeed or all fail.' },
  { st: 'Database Management', q: 'Which is NOT a SQL data type?', o: { A: 'INT', B: 'VARCHAR', C: 'FLOAT', D: 'ARRAY' }, c: 'D', ex: 'ARRAY is not standard SQL.' },

  // Computer Security
  { st: 'Computer Security', q: 'A computer virus is:', o: { A: 'A hardware fault', B: 'A malicious self-replicating program', C: 'An antivirus', D: 'A game' }, c: 'B', ex: 'Viruses replicate by attaching to programs.' },
  { st: 'Computer Security', q: 'Which is an antivirus?', o: { A: 'Norton', B: 'Oracle', C: 'MySQL', D: 'Linux' }, c: 'A', ex: 'Norton is antivirus software.' },
  { st: 'Computer Security', q: 'Encryption converts data into:', o: { A: 'Deleted form', B: 'Coded form', C: 'Compressed form', D: 'Backed up form' }, c: 'B', ex: 'Encryption encodes data for security.' },
  { st: 'Computer Security', q: 'A Trojan horse is:', o: { A: 'Hardware', B: 'Malware disguised as legitimate software', C: 'Antivirus', D: 'Firewall' }, c: 'B', ex: 'Trojans trick users into installing them.' },
  { st: 'Computer Security', q: 'A strong password has:', o: { A: 'Your name', B: '123456', C: 'Mix of uppercase, lowercase, numbers, symbols', D: 'Date of birth' }, c: 'C', ex: 'Strong passwords mix character types.' },
  { st: 'Computer Security', q: 'Malware stands for:', o: { A: 'Malicious Software', B: 'Managed Software', C: 'Machine Software', D: 'Multiple Software' }, c: 'A', ex: 'Malware = Malicious Software.' },
  { st: 'Computer Security', q: 'Two-factor authentication:', o: { A: 'Double password', B: 'Extra security using two verification methods', C: 'Two usernames', D: 'Two accounts' }, c: 'B', ex: '2FA uses two different verification forms.' },
  { st: 'Computer Security', q: 'Worms differ from viruses because:', o: { A: 'They cannot replicate', B: 'They spread without human interaction', C: 'They are harmless', D: 'They only affect hardware' }, c: 'B', ex: 'Worms self-replicate across networks.' },
  { st: 'Computer Security', q: 'SSL stands for:', o: { A: 'Secure Socket Layer', B: 'System Security Layer', C: 'Secure System Link', D: 'Standard Security Layer' }, c: 'A', ex: 'SSL = Secure Socket Layer.' },
  { st: 'Computer Security', q: 'Ransomware:', o: { A: 'Free software', B: 'Encrypts files and demands payment', C: 'Antivirus', D: 'Firewall' }, c: 'B', ex: 'Ransomware demands ransom for decryption.' },
  { st: 'Computer Security', q: 'Spyware:', o: { A: 'Protects computer', B: 'Secretly monitors user activity', C: 'Speeds up computer', D: 'Manages files' }, c: 'B', ex: 'Spyware collects user info secretly.' },
  { st: 'Computer Security', q: 'DDoS stands for:', o: { A: 'Direct Denial of Service', B: 'Distributed Denial of Service', C: 'Data Denial of Service', D: 'Digital Denial of Service' }, c: 'B', ex: 'DDoS floods targets with traffic.' },
  { st: 'Computer Security', q: 'Biometric authentication uses:', o: { A: 'Passwords only', B: 'Physical characteristics', C: 'Secret questions', D: 'PIN numbers' }, c: 'B', ex: 'Biometrics use fingerprint, face, iris.' },
  { st: 'Computer Security', q: 'HTTPS default port:', o: { A: '80', B: '21', C: '443', D: '25' }, c: 'C', ex: 'HTTPS uses port 443.' },
  { st: 'Computer Security', q: 'Social engineering is:', o: { A: 'Engineering social media', B: 'Manipulating people for confidential info', C: 'Building networks', D: 'UI design' }, c: 'B', ex: 'Social engineering exploits human psychology.' },
  { st: 'Computer Security', q: 'A honeypot is:', o: { A: 'A virus', B: 'A decoy to attract attackers', C: 'An encryption method', D: 'A password manager' }, c: 'B', ex: 'Honeypots detect and study attacks.' },
  { st: 'Computer Security', q: 'End-to-end encryption:', o: { A: 'Only sender encrypts', B: 'Only sender and recipient can read messages', C: 'Server encrypts', D: 'No encryption' }, c: 'B', ex: 'No third party can access the data.' },
  { st: 'Computer Security', q: 'Keylogger:', o: { A: 'A keyboard type', B: 'Software recording keystrokes', C: 'Key management tool', D: 'Password generator' }, c: 'B', ex: 'Keyloggers capture typed data.' },
  { st: 'Computer Security', q: 'Most common cyber attack:', o: { A: 'Phishing', B: 'SQL Injection', C: 'Man-in-the-middle', D: 'Brute force' }, c: 'A', ex: 'Phishing is the most common attack type.' },
  { st: 'Computer Security', q: 'AES stands for:', o: { A: 'Advanced Encryption Standard', B: 'Applied Encryption System', C: 'Advanced Electronic Security', D: 'Automated Encryption Standard' }, c: 'A', ex: 'AES = Advanced Encryption Standard.' },
  { st: 'Computer Security', q: 'Digital signature verifies:', o: { A: 'Physical identity', B: 'Authenticity and integrity of messages', C: 'Passwords', D: 'Emails' }, c: 'B', ex: 'Digital signatures verify sender and data integrity.' },
  { st: 'Computer Security', q: 'Cybercrime refers to:', o: { A: 'Legal computer use', B: 'Criminal activities using computers', C: 'Computer repair', D: 'Software development' }, c: 'B', ex: 'Cybercrime involves computer-based criminal acts.' },
  { st: 'Computer Security', q: 'A logic bomb is:', o: { A: 'A physical bomb', B: 'Malicious code triggered by a condition', C: 'A debugging tool', D: 'A firewall feature' }, c: 'B', ex: 'Logic bombs activate on specific conditions.' },
  { st: 'Computer Security', q: 'Hacking refers to:', o: { A: 'Legal testing', B: 'Unauthorized access to systems', C: 'Computer repair', D: 'Software installation' }, c: 'B', ex: 'Hacking is unauthorized system access.' },
  { st: 'Computer Security', q: 'Zero-day vulnerability:', o: { A: 'A fixed bug', B: 'An unknown flaw exploitable by attackers', C: 'A testing method', D: 'A backup type' }, c: 'B', ex: 'Zero-day flaws have no available patch.' },

  // Data Representation
  { st: 'Data Representation', q: 'Binary of decimal 10:', o: { A: '1010', B: '1001', C: '1100', D: '1110' }, c: 'A', ex: '10 = 8+2 = 1010 in binary.' },
  { st: 'Data Representation', q: 'Hexadecimal base is:', o: { A: '2', B: '8', C: '10', D: '16' }, c: 'D', ex: 'Hex uses base 16 (0-9, A-F).' },
  { st: 'Data Representation', q: 'Octal of binary 111:', o: { A: '5', B: '6', C: '7', D: '8' }, c: 'C', ex: '111 = 4+2+1 = 7.' },
  { st: 'Data Representation', q: 'Unicode represents:', o: { A: 'Only English', B: 'Characters from all languages', C: 'Only numbers', D: 'Only symbols' }, c: 'B', ex: 'Unicode covers all writing systems.' },
  { st: 'Data Representation', q: 'BCD stands for:', o: { A: 'Binary Coded Decimal', B: 'Binary Computer Data', C: 'Basic Coded Decimal', D: 'Binary Converted Data' }, c: 'A', ex: 'BCD = Binary Coded Decimal.' },
  { st: 'Data Representation', q: 'Hex of decimal 255:', o: { A: 'EF', B: 'FF', C: 'FE', D: 'F0' }, c: 'B', ex: '255 = 15×16+15 = FF.' },
  { st: 'Data Representation', q: 'One nibble equals:', o: { A: '2 bits', B: '4 bits', C: '8 bits', D: '16 bits' }, c: 'B', ex: 'A nibble = 4 bits = half a byte.' },
  { st: 'Data Representation', q: 'Decimal of binary 1100:', o: { A: '10', B: '11', C: '12', D: '13' }, c: 'C', ex: '1100 = 8+4 = 12.' },
  { st: 'Data Representation', q: '7-bit ASCII represents:', o: { A: '64', B: '128', C: '256', D: '512' }, c: 'B', ex: '2^7 = 128 characters.' },
  { st: 'Data Representation', q: 'Binary 1011 + 1101 =', o: { A: '10100', B: '11000', C: '11001', D: '11010' }, c: 'B', ex: '11+13 = 24 = 11000.' },
  { st: 'Data Representation', q: 'EBCDIC stands for:', o: { A: 'Extended Binary Coded Decimal Interchange Code', B: 'Electronic Binary Coded Decimal Interchange Code', C: 'Extended Binary Computer Data Interchange Code', D: 'Electronic Binary Computer Data Interchange Code' }, c: 'A', ex: 'EBCDIC is an 8-bit IBM encoding.' },
  { st: 'Data Representation', q: 'Octal base is:', o: { A: '2', B: '8', C: '10', D: '16' }, c: 'B', ex: 'Octal uses base 8 (digits 0-7).' },
  { st: 'Data Representation', q: '1 GB equals:', o: { A: '1000 MB', B: '1024 MB', C: '1024 KB', D: '1000 KB' }, c: 'B', ex: '1 GB = 1024 MB.' },
  { st: 'Data Representation', q: 'Float and Double represent:', o: { A: 'Integers', B: 'Decimal numbers', C: 'Characters', D: 'Booleans' }, c: 'B', ex: 'They store floating-point numbers.' },
  { st: 'Data Representation', q: 'Computers use which number system internally?', o: { A: 'Decimal', B: 'Octal', C: 'Binary', D: 'Hexadecimal' }, c: 'C', ex: 'Circuits work with binary (0/1).' },
  { st: 'Data Representation', q: "1's complement of 1010:", o: { A: '0101', B: '0110', C: '1001', D: '1010' }, c: 'A', ex: "Flip each bit: 1010 → 0101." },
  { st: 'Data Representation', q: 'Parity bit is used for:', o: { A: 'Compression', B: 'Error detection', C: 'Encryption', D: 'Storage' }, c: 'B', ex: 'Parity bits detect simple errors.' },
  { st: 'Data Representation', q: 'Binary of hex A:', o: { A: '1000', B: '1001', C: '1010', D: '1011' }, c: 'C', ex: 'A = 10 = 1010.' },
  { st: 'Data Representation', q: 'UTF-8 is:', o: { A: 'A database', B: 'A variable-width character encoding', C: 'An OS', D: 'A programming language' }, c: 'B', ex: 'UTF-8 encodes all Unicode characters.' },
  { st: 'Data Representation', q: '1 TB equals:', o: { A: '1000 GB', B: '1024 GB', C: '1024 MB', D: '1000 MB' }, c: 'B', ex: '1 TB = 1024 GB.' },
  { st: 'Data Representation', q: 'Hamming code is for:', o: { A: 'Compression', B: 'Error detection and correction', C: 'Encryption', D: 'Sorting' }, c: 'B', ex: 'Hamming code detects and corrects errors.' },
  { st: 'Data Representation', q: "2's complement of -1 in 8 bits:", o: { A: '10000001', B: '11111111', C: '11111110', D: '10000000' }, c: 'B', ex: '-1 = all 1s in 2\'s complement.' },
  { st: 'Data Representation', q: 'Gray code reduces errors in:', o: { A: 'Error detection', B: 'Digital-to-analog conversion', C: 'Compression', D: 'Encryption' }, c: 'B', ex: 'Gray code changes only one bit between values.' },
  { st: 'Data Representation', q: 'Excess-3 code is also called:', o: { A: 'Gray code', B: 'XS-3 code', C: 'BCD code', D: 'ASCII code' }, c: 'B', ex: 'Excess-3 = XS-3, a self-complementary BCD code.' },
  { st: 'Data Representation', q: 'Signed magnitude of -5 in 8 bits:', o: { A: '10000101', B: '11111010', C: '11111011', D: '10000100' }, c: 'A', ex: 'MSB=1 (negative), 5=0000101, so -5=10000101.' },

  // Software Engineering
  { st: 'Software Engineering', q: 'SDLC stands for:', o: { A: 'Software Development Life Cycle', B: 'System Development Life Cycle', C: 'Software Design Life Cycle', D: 'System Design Life Cycle' }, c: 'A', ex: 'SDLC = Software Development Life Cycle.' },
  { st: 'Software Engineering', q: 'Agile methodology emphasizes:', o: { A: 'Rigid planning', B: 'Iterative development and flexibility', C: 'No documentation', D: 'Sequential phases' }, c: 'B', ex: 'Agile focuses on iterative, flexible development.' },
  { st: 'Software Engineering', q: 'Waterfall model is:', o: { A: 'Iterative', B: 'Linear sequential', C: 'Spiral', D: 'Agile' }, c: 'B', ex: 'Waterfall follows a linear sequential approach.' },
  { st: 'Software Engineering', q: 'Testing done by end users is:', o: { A: 'Unit testing', B: 'Integration testing', C: 'Acceptance testing', D: 'Regression testing' }, c: 'C', ex: 'Acceptance testing validates user requirements.' },
  { st: 'Software Engineering', q: 'A bug in software is:', o: { A: 'An insect', B: 'An error or defect', C: 'A feature', D: 'A patch' }, c: 'B', ex: 'A bug is an error causing unexpected behavior.' },
  { st: 'Software Engineering', q: 'Version control systems track:', o: { A: 'User behavior', B: 'Changes to source code', C: 'Network traffic', D: 'Hardware performance' }, c: 'B', ex: 'VCS like Git track code changes over time.' },
  { st: 'Software Engineering', q: 'Black box testing tests:', o: { A: 'Internal code structure', B: 'Functionality without knowing internal code', C: 'Hardware', D: 'Network' }, c: 'B', ex: 'Black box tests functionality, not internal logic.' },
  { st: 'Software Engineering', q: 'IDE stands for:', o: { A: 'Integrated Development Environment', B: 'Internal Development Environment', C: 'Integrated Design Environment', D: 'Internal Design Environment' }, c: 'A', ex: 'IDE = Integrated Development Environment.' },
  { st: 'Software Engineering', q: 'Debugging is:', o: { A: 'Writing code', B: 'Finding and fixing errors', C: 'Testing', D: 'Deploying' }, c: 'B', ex: 'Debugging identifies and resolves defects.' },
  { st: 'Software Engineering', q: 'Open source software:', o: { A: 'Cannot be modified', B: 'Source code is freely available', C: 'Is always free of cost', D: 'Has no license' }, c: 'B', ex: 'Open source allows code access and modification.' },

  // Computer Architecture
  { st: 'Computer Architecture', q: 'Cache memory is:', o: { A: 'Slower than RAM', B: 'Faster than RAM but smaller', C: 'Same speed as RAM', D: 'A type of ROM' }, c: 'B', ex: 'Cache is fast, small memory between CPU and RAM.' },
  { st: 'Computer Architecture', q: 'RISC stands for:', o: { A: 'Reduced Instruction Set Computer', B: 'Random Instruction Set Computer', C: 'Rapid Instruction Set Computer', D: 'Reliable Instruction Set Computer' }, c: 'A', ex: 'RISC = Reduced Instruction Set Computer.' },
  { st: 'Computer Architecture', q: 'The program counter stores:', o: { A: 'Data', B: 'Address of the next instruction', C: 'Results', D: 'Intermediate values' }, c: 'B', ex: 'PC holds the address of the next instruction.' },
  { st: 'Computer Architecture', q: 'Bus in computer architecture is:', o: { A: 'A vehicle', B: 'A communication pathway between components', C: 'A type of memory', D: 'A processor' }, c: 'B', ex: 'Buses transfer data between CPU, memory, I/O.' },
  { st: 'Computer Architecture', q: 'CISC stands for:', o: { A: 'Complex Instruction Set Computer', B: 'Complete Instruction Set Computer', C: 'Central Instruction Set Computer', D: 'Common Instruction Set Computer' }, c: 'A', ex: 'CISC = Complex Instruction Set Computer.' },
  { st: 'Computer Architecture', q: 'Pipelining improves:', o: { A: 'Memory size', B: 'Instruction throughput', C: 'Storage capacity', D: 'Network speed' }, c: 'B', ex: 'Pipelining overlaps instruction execution stages.' },
  { st: 'Computer Architecture', q: 'Von Neumann architecture uses:', o: { A: 'Separate memory for data and instructions', B: 'Single memory for both data and instructions', C: 'No memory', D: 'Only ROM' }, c: 'B', ex: 'Von Neumann uses shared memory for both.' },
  { st: 'Computer Architecture', q: 'Clock speed of a processor is measured in:', o: { A: 'Bytes', B: 'GHz', C: 'Watts', D: 'Pixels' }, c: 'B', ex: 'Clock speed is measured in GHz (Gigahertz).' },
  { st: 'Computer Architecture', q: 'A 64-bit processor can handle:', o: { A: 'More data per clock cycle than 32-bit', B: 'Less data than 32-bit', C: 'Same as 32-bit', D: 'Only 64 bits total' }, c: 'A', ex: '64-bit processors handle more data per cycle.' },
  { st: 'Computer Architecture', q: 'DMA stands for:', o: { A: 'Direct Memory Access', B: 'Digital Memory Access', C: 'Dynamic Memory Allocation', D: 'Direct Memory Allocation' }, c: 'A', ex: 'DMA allows hardware to access memory without CPU.' },
]

const result = []
let id = 1
raw.forEach((q) => {
  result.push({
    id: `comp_${id}`,
    subject: 'Computer',
    subtopic: q.st,
    exam: exams[id % exams.length],
    level: 'Mains',
    year: years[id % years.length],
    question: q.q,
    options: q.o,
    correct: q.c,
    explanation: q.ex,
  })
  id++
})

fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'data', 'computer.json'),
  JSON.stringify(result, null, 2)
)
console.log(`Generated ${result.length} Computer questions`)
